name: release-drafter

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, edited]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  draft:
    name: draft next release notes
    runs-on: ubuntu-latest
    permissions:
      contents: write # create / update draft release
      pull-requests: read
    steps:
      - name: Draft
        uses: release-drafter/release-drafter@da8b9b696abad2ad997580e49f4c1c2e03cc2bd2 # v7.3.0
        # Config lives in .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
