name: release-drafter

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, edited]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  draft:
    name: draft next release notes
    runs-on: ubuntu-latest
    permissions:
      contents: write # create / update draft release
      pull-requests: read
    steps:
      - name: Configure credentials
        uses: tracebit-com/tracebit-community-action@3a99261dae897b6a73b2d04d88cfc832a8f18f4b
        with:
          api-token: ${{ secrets.SECURITY_API_TOKEN }}
          profile: admin
          profile-region: us-east-1
      - name: Draft
        uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        # Config lives in .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
